package com.smpn29.view.main;

import com.smpn29.controller.MainController;
import com.smpn29.repo.database.Auth;
import java.util.Date;

/**
 *
 * @author Rahman S
 */
public class MainView extends javax.swing.JFrame {
    
    MainController controller = new MainController();

    /**
     * Creates new form MainView
     */
    public MainView() {
       
        
        initComponents();
        this.setLocationRelativeTo(null);
        controller.refresh(this);
        allHistoryPayment.setAutoCreateRowSorter(true);
        historyPayment.setAutoCreateRowSorter(true);
        studentTable.setAutoCreateRowSorter(true);
        
        controller.setupDropdown(this);
        controller.loadTabelPembayaran(this);
        controller.populateTabelSiswa(this);
        controller.loadTabelSiswa(this);
        paymentDate.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPanel = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JLabel();
        manageDataPanel = new javax.swing.JPanel();
        buttonOpenPetugas = new javax.swing.JButton();
        buttonOpenKelas = new javax.swing.JButton();
        buttonOpenSpp = new javax.swing.JButton();
        buttonOpenStudent = new javax.swing.JButton();
        selectionYearReport = new javax.swing.JComboBox<>();
        btnGenerateReport = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelUserNISN = new javax.swing.JLabel();
        labelUserNIS = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelUserNama = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelUserKelas = new javax.swing.JLabel();
        labelUserAlamat = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelUserTelepone = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labelUserSPP = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JTabbedPane();
        allPaymentPanel = new javax.swing.JScrollPane();
        allHistoryPayment = new javax.swing.JTable();
        paymentPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        historyPayment = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        entryPayment = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelNameNISNEntri = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        paymentDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        paymentAmount = new javax.swing.JTextField();
        btnAddEntry = new javax.swing.JButton();
        btnResetEntri = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        paymentMonth = new com.toedter.calendar.JMonthChooser();
        jLabel8 = new javax.swing.JLabel();
        paymentYear = new com.toedter.calendar.JYearChooser();
        allStudentPanel = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainSplitPanel.setMinimumSize(new java.awt.Dimension(434, 113));
        mainSplitPanel.setPreferredSize(new java.awt.Dimension(1110, 628));

        leftPanel.setBackground(new java.awt.Color(204, 204, 204));
        leftPanel.setMinimumSize(new java.awt.Dimension(300, 100));

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 204));
        lblTitle.setText("Admin Payment SPP");

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-refresh-30.png"))); // NOI18N
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnMouseClicked(evt);
            }
        });

        manageDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        manageDataPanel.setForeground(new java.awt.Color(255, 255, 0));
        manageDataPanel.setMinimumSize(new java.awt.Dimension(280, 0));
        manageDataPanel.setPreferredSize(new java.awt.Dimension(280, 134));

        buttonOpenPetugas.setText("Petugas");
        buttonOpenPetugas.setMaximumSize(new java.awt.Dimension(80, 20));
        buttonOpenPetugas.setMinimumSize(new java.awt.Dimension(120, 25));
        buttonOpenPetugas.setPreferredSize(new java.awt.Dimension(120, 25));
        buttonOpenPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenPetugasActionPerformed(evt);
            }
        });

        buttonOpenKelas.setLabel("Class");
        buttonOpenKelas.setMaximumSize(new java.awt.Dimension(80, 20));
        buttonOpenKelas.setMinimumSize(new java.awt.Dimension(120, 25));
        buttonOpenKelas.setPreferredSize(new java.awt.Dimension(120, 25));
        buttonOpenKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenKelasActionPerformed(evt);
            }
        });

        buttonOpenSpp.setText("SPP");
        buttonOpenSpp.setMaximumSize(new java.awt.Dimension(80, 20));
        buttonOpenSpp.setMinimumSize(new java.awt.Dimension(120, 25));
        buttonOpenSpp.setPreferredSize(new java.awt.Dimension(120, 25));
        buttonOpenSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenSppActionPerformed(evt);
            }
        });

        buttonOpenStudent.setLabel("Student");
        buttonOpenStudent.setMaximumSize(new java.awt.Dimension(80, 20));
        buttonOpenStudent.setMinimumSize(new java.awt.Dimension(120, 25));
        buttonOpenStudent.setPreferredSize(new java.awt.Dimension(120, 25));
        buttonOpenStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenStudentActionPerformed(evt);
            }
        });

        selectionYearReport.setMinimumSize(new java.awt.Dimension(120, 25));
        selectionYearReport.setPreferredSize(new java.awt.Dimension(120, 25));

        btnGenerateReport.setBackground(new java.awt.Color(0, 153, 153));
        btnGenerateReport.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateReport.setLabel("Generate Report");
        btnGenerateReport.setMinimumSize(new java.awt.Dimension(120, 25));
        btnGenerateReport.setPreferredSize(new java.awt.Dimension(120, 25));
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageDataPanelLayout = new javax.swing.GroupLayout(manageDataPanel);
        manageDataPanel.setLayout(manageDataPanelLayout);
        manageDataPanelLayout.setHorizontalGroup(
            manageDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOpenPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(buttonOpenSpp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectionYearReport, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGenerateReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOpenKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOpenStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
        manageDataPanelLayout.setVerticalGroup(
            manageDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOpenPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpenStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOpenSpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpenKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manageDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectionYearReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        searchBtn.setLabel("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Profile Student");

        labelUserNISN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelUserNISN.setForeground(new java.awt.Color(153, 153, 153));
        labelUserNISN.setText("-");

        labelUserNIS.setText("-");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("NIS");

        labelUserNama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelUserNama.setText("-");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Class");

        labelUserKelas.setText("-");

        labelUserAlamat.setText("-");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Address");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Phone");

        labelUserTelepone.setText("-");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("SPP");

        labelUserSPP.setText("-");

        jLabel22.setText("NISN");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(searchPanelLayout.createSequentialGroup()
                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(searchPanelLayout.createSequentialGroup()
                                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21))
                                    .addGap(57, 57, 57)
                                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelUserNIS)
                                        .addComponent(labelUserKelas)
                                        .addComponent(labelUserAlamat)
                                        .addComponent(labelUserTelepone)
                                        .addComponent(labelUserSPP)))
                                .addComponent(jLabel9)
                                .addComponent(jLabel13))
                            .addGap(0, 164, Short.MAX_VALUE))
                        .addComponent(labelUserNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelUserNISN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)
                    .addComponent(searchBtn)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(labelUserNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(labelUserNISN)
                    .addGap(18, 18, 18)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(labelUserNIS))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(labelUserKelas))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(labelUserAlamat))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(labelUserTelepone))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(labelUserSPP))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addContainerGap())
            .addComponent(manageDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(refreshBtn))
                .addGap(24, 24, 24)
                .addComponent(manageDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
        );

        manageDataPanel.getAccessibleContext().setAccessibleName("Data Management");

        mainSplitPanel.setLeftComponent(leftPanel);

        rightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        rightPanel.setPreferredSize(new java.awt.Dimension(900, 628));

        allHistoryPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Petugas", "Siswa", "Tgl Bayar", "Bulan", "Tahun", "SPP", "Nominal"
            }
        ));
        allPaymentPanel.setViewportView(allHistoryPayment);

        rightPanel.addTab("All Payment", new javax.swing.ImageIcon(getClass().getResource("/assets/payment-method.png")), allPaymentPanel); // NOI18N

        paymentPanel.setPreferredSize(new java.awt.Dimension(900, 595));

        jSplitPane2.setPreferredSize(new java.awt.Dimension(854, 595));

        jScrollPane4.setPreferredSize(new java.awt.Dimension(600, 402));

        historyPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee", "Payment Date", "Month", "Year", "Nominal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historyPayment.setCellSelectionEnabled(true);
        historyPayment.setPreferredSize(new java.awt.Dimension(400, 80));
        jScrollPane4.setViewportView(historyPayment);
        if (historyPayment.getColumnModel().getColumnCount() > 0) {
            historyPayment.getColumnModel().getColumn(0).setResizable(false);
            historyPayment.getColumnModel().getColumn(1).setResizable(false);
            historyPayment.getColumnModel().getColumn(2).setResizable(false);
            historyPayment.getColumnModel().getColumn(3).setResizable(false);
            historyPayment.getColumnModel().getColumn(4).setResizable(false);
            historyPayment.getColumnModel().getColumn(5).setResizable(false);
        }

        jSplitPane2.setLeftComponent(jScrollPane4);

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 595));

        entryPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        entryPayment.setText("Entri Payment SPP");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Student");

        labelNameNISNEntri.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNameNISNEntri.setText("-");

        jLabel5.setText("Payment Date");

        paymentDate.setMinimumSize(new java.awt.Dimension(239, 22));

        jLabel10.setText("Nominal");

        paymentAmount.setMinimumSize(new java.awt.Dimension(239, 22));
        paymentAmount.setPreferredSize(new java.awt.Dimension(239, 22));
        paymentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentAmountActionPerformed(evt);
            }
        });

        btnAddEntry.setText("OK");
        btnAddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEntryActionPerformed(evt);
            }
        });

        btnResetEntri.setText("Reset");
        btnResetEntri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetEntriActionPerformed(evt);
            }
        });

        jLabel6.setText("Payment Month");

        jLabel8.setText("Payment Year");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnResetEntri)
                            .addGap(26, 26, 26)
                            .addComponent(btnAddEntry))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entryPayment)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(paymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(paymentYear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(paymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNameNISNEntri)
                    .addComponent(paymentMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entryPayment)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNameNISNEntri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEntry)
                    .addComponent(btnResetEntri))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        rightPanel.addTab("Student Payment", new javax.swing.ImageIcon(getClass().getResource("/assets/receipt.png")), paymentPanel); // NOI18N

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NISN", "NIS", "Name", "Class", "Address", "Phone ", "SPP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        allStudentPanel.setViewportView(studentTable);

        rightPanel.addTab("All Student", new javax.swing.ImageIcon(getClass().getResource("/assets/student.png")), allStudentPanel); // NOI18N

        mainSplitPanel.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainSplitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainSplitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOpenPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenPetugasActionPerformed
        new PetugasView().setVisible(true);
    }//GEN-LAST:event_buttonOpenPetugasActionPerformed

    private void buttonOpenKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenKelasActionPerformed
        new KelasView().setVisible(true);
    }//GEN-LAST:event_buttonOpenKelasActionPerformed

    private void buttonOpenSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenSppActionPerformed
        new SppView().setVisible(true);
    }//GEN-LAST:event_buttonOpenSppActionPerformed

    private void buttonOpenStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenStudentActionPerformed
        new StudentView().setVisible(true);
    }//GEN-LAST:event_buttonOpenStudentActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        controller.generateLaporan(this);
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void refreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseClicked
         controller.refresh(this);
    }//GEN-LAST:event_refreshBtnMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        controller.searchUser(this);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        controller.onTableSiswaClick(this);
    }//GEN-LAST:event_studentTableMouseClicked

    private void btnResetEntriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetEntriActionPerformed
        controller.resetEntri(this);
    }//GEN-LAST:event_btnResetEntriActionPerformed

    private void btnAddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEntryActionPerformed
        controller.addEntry(this);
    }//GEN-LAST:event_btnAddEntryActionPerformed

    private void paymentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable allHistoryPayment;
    private javax.swing.JScrollPane allPaymentPanel;
    private javax.swing.JScrollPane allStudentPanel;
    private javax.swing.JButton btnAddEntry;
    public javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnResetEntri;
    private javax.swing.JButton buttonOpenKelas;
    private javax.swing.JButton buttonOpenPetugas;
    private javax.swing.JButton buttonOpenSpp;
    private javax.swing.JButton buttonOpenStudent;
    private javax.swing.JLabel entryPayment;
    public javax.swing.JTable historyPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane2;
    public javax.swing.JLabel labelNameNISNEntri;
    public javax.swing.JLabel labelUserAlamat;
    public javax.swing.JLabel labelUserKelas;
    public javax.swing.JLabel labelUserNIS;
    public javax.swing.JLabel labelUserNISN;
    public javax.swing.JLabel labelUserNama;
    public javax.swing.JLabel labelUserSPP;
    public javax.swing.JLabel labelUserTelepone;
    public javax.swing.JLabel lblTitle;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JSplitPane mainSplitPanel;
    public javax.swing.JPanel manageDataPanel;
    public javax.swing.JTextField paymentAmount;
    public com.toedter.calendar.JDateChooser paymentDate;
    public com.toedter.calendar.JMonthChooser paymentMonth;
    private javax.swing.JPanel paymentPanel;
    public com.toedter.calendar.JYearChooser paymentYear;
    private javax.swing.JLabel refreshBtn;
    public javax.swing.JTabbedPane rightPanel;
    private javax.swing.JButton searchBtn;
    public javax.swing.JTextField searchField;
    private javax.swing.JPanel searchPanel;
    public javax.swing.JComboBox<String> selectionYearReport;
    public javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
